"""empty message

Revision ID: 1526f0cb6c8e
Revises: 876ea121d337
Create Date: 2024-01-29 14:08:47.489862

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1526f0cb6c8e'
down_revision = '876ea121d337'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('file_store',
    sa.Column('id', sa.String(length=120), nullable=False),
    sa.Column('user_id', sa.String(length=120), nullable=False),
    sa.Column('collection_name', sa.String(length=255), nullable=False),
    sa.Column('collection_id', sa.String(length=150), nullable=True),
    sa.Column('document_name', sa.String(length=255), nullable=False),
    sa.Column('document_file_path', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user_register.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('file_store')
    # ### end Alembic commands ###
