"""empty message

Revision ID: 167e84eb90ac
Revises: 1526f0cb6c8e
Create Date: 2024-01-29 17:33:53.642027

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '167e84eb90ac'
down_revision = '1526f0cb6c8e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_communication',
    sa.Column('id', sa.String(length=120), nullable=False),
    sa.Column('user_id', sa.String(length=120), nullable=False),
    sa.Column('role', sa.String(length=120), nullable=False),
    sa.Column('chat_data', sa.TEXT(), nullable=False),
    sa.Column('chat_index', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('date_created', sa.Date(), nullable=True),
    sa.Column('time_created', sa.Time(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user_register.id'], ),
    sa.PrimaryKeyConstraint('id', 'chat_index')
    )
    op.create_table('file_store',
    sa.Column('id', sa.String(length=120), nullable=False),
    sa.Column('user_id', sa.String(length=120), nullable=False),
    sa.Column('collection_name', sa.String(length=255), nullable=False),
    sa.Column('collection_id', sa.String(length=150), nullable=True),
    sa.Column('document_name', sa.String(length=255), nullable=False),
    sa.Column('document_file_path', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user_register.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('file_store')
    op.drop_table('chat_communication')
    # ### end Alembic commands ###
