"""empty message

Revision ID: 77eb2380ed2d
Revises: 
Create Date: 2024-01-29 10:04:16.861533

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '77eb2380ed2d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_register',
    sa.Column('id', sa.String(length=120), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('username', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=250), nullable=False),
    sa.Column('password', sa.String(length=250), nullable=False),
    sa.Column('created_by', sa.String(length=120), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('chat_communication',
    sa.Column('id', sa.String(length=120), nullable=False),
    sa.Column('user_id', sa.String(length=120), nullable=False),
    sa.Column('role', sa.String(length=120), nullable=False),
    sa.Column('chat_data', sa.TEXT(), nullable=False),
    sa.Column('chat_index', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('date_created', sa.Date(), nullable=True),
    sa.Column('time_created', sa.Time(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user_register.id'], ),
    sa.PrimaryKeyConstraint('id', 'chat_index')
    )
    op.create_table('file_store',
    sa.Column('id', sa.String(length=120), nullable=False),
    sa.Column('user_id', sa.String(length=120), nullable=False),
    sa.Column('document_name', sa.String(length=255), nullable=False),
    sa.Column('document_file_path', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user_register.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('file_store')
    op.drop_table('chat_communication')
    op.drop_table('user_register')
    # ### end Alembic commands ###
