"""empty message

Revision ID: 876ea121d337
Revises: 77eb2380ed2d
Create Date: 2024-01-29 10:17:27.034357

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '876ea121d337'
down_revision = '77eb2380ed2d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('file_store', schema=None) as batch_op:
        batch_op.add_column(sa.Column('collection_name', sa.String(length=255), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('file_store', schema=None) as batch_op:
        batch_op.drop_column('collection_name')

    # ### end Alembic commands ###
